name: 一键触发
on:
    workflow_dispatch:
jobs:
    test-job:
        runs-on: macos-latest
        steps:
            - name: 同步代码
              uses: actions/checkout@v5

            - name: 打印提示
              run: echo "✅MacOS流水线手动执行成功"