name: IOS打包IPA并签名V1

on: 
  workflow_dispatch:

jobs:
  build-ios:
    name: IOS打包
    runs-on: macos-latest

    steps:
      - name: P12密钥导入
        uses: apple-actions/import-codesign-certs@v7
        with:
          p12-file-base64: ${{ secrets.IOS_P12_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}
